// 产品数据
const productsData = {
  1: {
    id: 1,
    name: "六轴协作机器人",
    model: "ZL-ROBOT-10L",
    category: "工业机器人",
    categoryKey: "robot",
    price: 85000,
    originalPrice: 95000,
    badge: "热销",
    description:
      "高精度、高灵活性的六轴协作机器人，适用于装配、搬运、焊接等多种应用场景。采用先进的力控技术，可实现人机协作安全作业。",
    specs: {
      负载能力: "10kg",
      臂展: "1300mm",
      重复定位精度: "±0.02mm",
      最大速度: "2m/s",
      轴数: "6轴",
      防护等级: "IP67",
      通讯接口: "EtherCAT, Modbus TCP",
      工作温度: "0-45°C",
      重量: "55kg",
      电源: "220V AC",
    },
    features: [
      "人机协作安全设计",
      "高精度力控系统",
      "快速示教编程",
      "支持多机器人协同",
      "开放式API接口",
      "智能碰撞检测",
    ],
    applications: [
      "电子零部件装配",
      "汽车零部件焊接",
      "物料搬运与码垛",
      "精密检测与测量",
      "抛光与打磨",
      "3D视觉引导抓取",
    ],
    technicalSupport: [
      "24小时技术支持热线",
      "免费上门安装调试",
      "一年整机保修服务",
      "终身技术咨询服务",
      "定期维护保养提醒",
      "软件版本免费升级",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "2.5MB" },
      { name: "用户手册", type: "PDF", size: "5.2MB" },
      { name: "CAD模型", type: "STEP", size: "8.1MB" },
      { name: "编程指南", type: "PDF", size: "3.8MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [2, 6, 3],
  },
  2: {
    id: 2,
    name: "智能PLC控制器",
    model: "ZL-PLC-500",
    category: "控制系统",
    categoryKey: "control",
    price: 12800,
    originalPrice: 14800,
    badge: "新品",
    description:
      "高性能可编程逻辑控制器，采用最新一代处理器架构，支持多种工业通讯协议，适用于复杂工业控制场景。",
    specs: {
      处理器: "ARM Cortex-A9 1GHz",
      最大IO点数: "256点",
      程序内存: "64MB",
      数据内存: "128MB",
      通讯接口: "EtherNet/IP, PROFINET, Modbus TCP",
      扩展模块: "最多32个",
      高速计数器: "8通道 1MHz",
      PWM输出: "4通道",
      防护等级: "IP20",
      工作温度: "-10-55°C",
    },
    features: [
      "超高速运算处理能力",
      "丰富的通讯协议支持",
      "模块化扩展设计",
      "内置Web服务器",
      "支持云端数据交互",
      "图形化编程环境",
    ],
    applications: [
      "自动化生产线控制",
      "机器人控制系统",
      "包装机械控制",
      "物流分拣系统",
      "智能仓储管理",
      "能源监控系统",
    ],
    technicalSupport: [
      "12个月质保服务",
      "免费编程培训",
      "远程技术支持",
      "项目方案设计咨询",
      "7×24小时紧急支持",
      "固件免费升级",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "1.8MB" },
      { name: "编程手册", type: "PDF", size: "12.5MB" },
      { name: "EDD文件", type: "ZIP", size: "2.1MB" },
      { name: "示例程序", type: "ZIP", size: "4.7MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [1, 4, 5],
  },
  3: {
    id: 3,
    name: "机器视觉检测系统",
    model: "ZL-VISION-4K",
    category: "视觉系统",
    categoryKey: "vision",
    price: 35000,
    originalPrice: 42000,
    badge: "",
    description:
      "高速高精度视觉检测系统，集成深度学习AI算法，支持缺陷检测、定位识别、尺寸测量等多种应用。",
    specs: {
      相机分辨率: "4096×3072 (12MP)",
      帧率: "30fps @ 全分辨率",
      像素深度: "12位",
      镜头接口: "C-Mount",
      照明系统: "环形光源+同轴光源",
      AI处理器: "NVIDIA Jetson Xavier NX",
      检测精度: "±0.01mm",
      通讯接口: "GigE Vision, USB3.0",
      操作系统: "Linux Ubuntu",
      工作温度: "0-40°C",
    },
    features: [
      "深度学习缺陷检测",
      "亚像素级测量精度",
      "360度全方位检测",
      "自动光学变焦",
      "多相机协同工作",
      "实时数据统计分析",
    ],
    applications: [
      "PCB板缺陷检测",
      "电子元件外观检测",
      "产品尺寸测量",
      "条码二维码读取",
      "机器人视觉引导",
      "包装印刷质量检测",
    ],
    technicalSupport: [
      "一年质保服务",
      "免费算法优化",
      "现场安装调试",
      "操作培训服务",
      "定制化算法开发",
      "定期系统维护",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "3.2MB" },
      { name: "软件操作手册", type: "PDF", size: "8.6MB" },
      { name: "SDK开发包", type: "ZIP", size: "15.3MB" },
      { name: "算法模型库", type: "ZIP", size: "25.8MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [1, 2, 4],
  },
  4: {
    id: 4,
    name: "激光测距传感器",
    model: "ZL-LRF-100H",
    category: "传感器",
    categoryKey: "sensor",
    price: 2800,
    originalPrice: 3200,
    badge: "",
    description:
      "高精度激光测距传感器，采用TOF飞行时间技术，适用于工业自动化、仓储物流、智能交通等领域。",
    specs: {
      测量量程: "0.1-100m",
      测量精度: "±1mm",
      重复精度: "±0.5mm",
      采样频率: "10kHz",
      激光波长: "905nm",
      激光等级: "Class 1 (眼安全)",
      输出接口: "RS485, SSI, CAN",
      供电电压: "10-30V DC",
      防护等级: "IP67",
      工作温度: "-40-60°C",
    },
    features: [
      "超高测量精度",
      "抗干扰能力强",
      "支持多种输出接口",
      "微型化设计",
      "低功耗运行",
      "内置温度补偿",
    ],
    applications: [
      "AGV/AMR定位导航",
      "仓储物流高度测量",
      "行车防撞预警",
      "物料堆垛检测",
      "车辆轮廓检测",
      "建筑尺寸测量",
    ],
    technicalSupport: [
      "18个月质保",
      "免费技术咨询",
      "应用方案支持",
      "定制化开发服务",
      "批量测试支持",
      "固件在线升级",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "1.2MB" },
      { name: "通信协议手册", type: "PDF", size: "850KB" },
      { name: "配置软件", type: "ZIP", size: "5.2MB" },
      { name: "3D模型", type: "STEP", size: "1.5MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [5, 2, 3],
  },
  5: {
    id: 5,
    name: "伺服电动缸",
    model: "ZL-EC-10KN",
    category: "执行机构",
    categoryKey: "actuator",
    price: 8500,
    originalPrice: 9800,
    badge: "",
    description:
      "高精度伺服电动缸，替代传统液压缸和气缸，实现精确位置和力控制，节能环保，维护成本低。",
    specs: {
      额定推力: "10kN",
      最大推力: "15kN",
      行程范围: "50-1000mm",
      最大速度: "1m/s",
      重复定位精度: "±0.01mm",
      丝杠导程: "5/10/20mm",
      电机类型: "伺服电机",
      编码器: "17位绝对值",
      防护等级: "IP65",
      工作温度: "-10-70°C",
    },
    features: [
      "高精度位置控制",
      "闭环力控系统",
      "高响应速度",
      "长寿命低噪音",
      "免维护设计",
      "多种安装方式",
    ],
    applications: [
      "六自由度平台",
      "压力机设备",
      "模拟仿真平台",
      "材料试验机",
      "自动化装配线",
      "医疗设备应用",
    ],
    technicalSupport: [
      "12个月质保",
      "免费选型指导",
      "安装调试支持",
      "定制化设计服务",
      "快速维修服务",
      "定期巡检服务",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "2.1MB" },
      { name: "安装手册", type: "PDF", size: "3.5MB" },
      { name: "CAD模型库", type: "ZIP", size: "12.8MB" },
      { name: "控制软件", type: "ZIP", size: "8.2MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [2, 4, 1],
  },
  6: {
    id: 6,
    name: "SCARA机器人",
    model: "ZL-SCARA-600",
    category: "工业机器人",
    categoryKey: "robot",
    price: 58000,
    originalPrice: 65000,
    badge: "推荐",
    description:
      "高速SCARA机器人，专为电子装配、包装、分拣等应用设计，具有极高的速度和重复定位精度。",
    specs: {
      负载能力: "6kg",
      臂展: "600mm",
      重复定位精度: "±0.01mm",
      标准循环时间: "0.4秒",
      Z轴行程: "200mm",
      旋转范围: "±170°",
      防护等级: "IP54",
      通讯接口: "EtherCAT",
      工作温度: "0-40°C",
      重量: "35kg",
    },
    features: [
      "超高速作业能力",
      "超高重复精度",
      "紧凑空间设计",
      "多种手爪兼容",
      "视觉系统集成",
      "传送带跟踪功能",
    ],
    applications: [
      "SMT贴片装配",
      "LED面板组装",
      "电池片搬运",
      "食品包装分拣",
      "医疗器件装配",
      "3C电子检测",
    ],
    technicalSupport: [
      "一年整机保修",
      "免费现场安装",
      "操作培训服务",
      "应用方案支持",
      "24小时响应服务",
      "预防性维护服务",
    ],
    downloads: [
      { name: "产品规格书", type: "PDF", size: "2.8MB" },
      { name: "用户操作手册", type: "PDF", size: "6.3MB" },
      { name: "3D模型", type: "STEP", size: "10.2MB" },
      { name: "编程示例", type: "ZIP", size: "3.6MB" },
    ],
    images: ["main", "angle1", "angle2", "detail1", "detail2"],
    relatedProducts: [1, 3, 2],
  },
};

// 获取URL参数中的产品ID
function getProductId() {
  const urlParams = new URLSearchParams(window.location.search);
  return urlParams.get("id") || 1;
}

// 根据ID获取产品数据
function getProductData(id) {
  return productsData[id] || productsData[1];
}

// 获取相关产品数据
function getRelatedProducts(relatedIds) {
  return relatedIds.map((id) => productsData[id]).filter(Boolean);
}
